-- Counting/progress of a block (see blockRunnerUtils.computeUnits) used to group
-- by exercise_id only. If the same exercise appears several times in different pairs
-- of the same block (e.g. "door pull" in several superset pairs), logged sets
-- of one pair were wrongly counted as progress of another pair -- a pair could thus
-- count as "done" before it had even started.
--
-- plan_block_exercise_id identifies the concrete entry (the "slot") within the
-- frozen day_snapshot, independent of the (possibly repeated) exercise_id.
-- Deliberately without a foreign key to plan_block_exercises: the day_snapshot is frozen at
-- session start, later changes/deletions to the plan must not cascade into historical
-- sets. Existing rows stay NULL and fall back to the old (exercise_id-based) behaviour
-- in the frontend.
ALTER TABLE logged_sets ADD COLUMN plan_block_exercise_id INTEGER;
